### ISSUE TITLE
sdk-k8s has dataraces

### ISSUE THREAD

**Issue by denis-tingaikin** [networkservicemesh/sdk-k8s#191]
## Problem

See at logs from: https://github.com/networkservicemesh/sdk-k8s/runs/2851515757?check_suite_focus=true

## Defenition of done

Fix all data races.

**Comment by glazychev-art** [comment]
Found a data race in `kubernetes/client-go`.
The corresponding issue was created:
https://github.com/kubernetes/kubernetes/issues/103148

**Comment by glazychev-art** [comment]
The PR for this issue was merged:
https://github.com/kubernetes/kubernetes/pull/103487

Now we are waiting for new `client-go` release with this fix
