### ISSUE TITLE
ETCD registry watch starts receiving tons of events

### ISSUE THREAD

**Issue by Bolodya1997** [networkservicemesh/sdk-k8s#207]
## Place in code
https://github.com/networkservicemesh/sdk-k8s/blob/6a4dea64961fcdb8dee6b5023d7259106907bcfd/pkg/registry/etcd/nse_server.go#L122-L132

## Expected behavior
This code should receive updates only on NSE updates (Register, Unregister).

## Current behavior
After some time working (30-40 min) it starts receiving tons of events with `event.Object == nil`. It results in looping on `continue` and using huge amount of CPU resources.

**Comment by denis-tingaikin** [comment]
Do you have idea on why it is happening?
