### ISSUE TITLE
Watching NSE Find leaks resources

### ISSUE THREAD

**Issue by Bolodya1997** [networkservicemesh/sdk-k8s#243]
## Current behavior
Watching NSE Find leaks resources. Looks like it is somehow related to `client.NetworkservicemeshV1().NetworkServiceEndpoints().Watch()`.
![image](https://user-images.githubusercontent.com/20160689/134165335-a4a94f45-3af6-4cdc-ad86-632c8f947083.png)
[registry-k8s-5b77d84b85-lgxn4.pb.gz](https://github.com/networkservicemesh/sdk-k8s/files/7215251/registry-k8s-5b77d84b85-lgxn4.pb.gz)

## Logs
[registry.log.zip](https://github.com/networkservicemesh/sdk-k8s/files/7202830/registry.log.zip)

**Comment by denis-tingaikin** [comment]
Please attach the profile output file. The picture doesn't help to understand what is going on. Thanks.

**Comment by Bolodya1997** [comment]
> Please attach the profile output file. The picture doesn't help to understand what is going on. Thanks.

Fixed.
